### PR TITLE
Fix for inotify for vim editor

### PR DESCRIPTION
**Pull request by ont**
Some editors like vim do writes through temporary file. That temporary
file then renamed to original one.

### CODE REVIEW

**Comment by mirmik** [comment]
good job

**Comment by mirmik** [comment]
Unfortunately, there may be problems with access permissions rights to some files in the directory. I couldn’t figure out how to solve this quickly, and so for now I’ve rolled back the commit. 66d9ed78501c73a56d0f4

**Comment by mirmik** [comment]
In general, our friend @sevikk, who ported zencad to mac, was forced to replace inotify with a mechanism for periodic file checks (since there is no inotify on mac). I thought this mechanism should be legalized, since it will not only be cross platform with OS, but also with respect to editors.

**Comment by sevikkk** [comment]
There are some cross platform libs for things like this, but I'm not sure we actually ned this for tracking of single file.

And for more general problem when there are imports and so on, there are ready to go solutions, like  https://github.com/fyrestone/pydevd_reload. And probably there is a sense to just use them and do not reinvent the wheel.

**Comment by mirmik** [comment]
It would be nice to add import dependency.
I will study this library.

**Pull request merged**
